### ISSUE TITLE
SetNextPrimaryFire does not exist, which can lead to a potential server overload due to infinite RPM

### ISSUE THREAD

**Issue by The1337Gh0st** [FreshGarry/TTT-Detective-Playercam#1]
Reposting this from Cpt.Haxray's bug report on Steam as it hasn't been added in here yet:

SetNextPrimaryFire is not defined in the addon's code, which means that this weapon could have theoretically infinite RPM, which can lead to a server crash if utilized properly. This can be fixed by adding in the following code:
self:SetNextPrimaryFire( CurTime() + self.Primary.Delay )

**Comment by FreshGarry** [comment]
Should be fixed with the last update.
